luisorduz/juridico_front

src/components/xray/charts/GraficaProcesosPorAseguradora.vue
src/components/xray/sidebars/SideBarStyle1.vue
src/views/Dashboards/DashboardGerencia.vue
src/views/Process/ShowProcess.vue

Se implementó gráfica de procesos por aseguradora en el panel gerencial

FUSION [JUR-72] feature grafica de polizas en el panel gerencial con release 1.1.0

---

src/views/Process/ShowProcess.vue

Se modificó el nombre de la pestaña links en showprocess a  Documentos del proceso

FUSION [JUR-78] cambio título pestaña links con release-1.1.0

---

src/components/xray/charts/GraficaInformacionPorRiesgo.vue
src/components/xray/charts/GraficaProcesosPorAseguradora.vue
src/views/Process/ShowProcess.vue
src/views/ProcessLaboralesOrdinarios/ProcessLaboralesList.vue

fusión release-1.1.0 se eliminaron console.logs con main

---

src/views/Process/ShowProcess.vue

Se implementó distintivo al involucrado principal para visualizarlo mejor tanto en info proceso como en la lista de involucrados

[JUR-81] involucrado principal lista implicados con release-1.1.0

---

src/views/Process/ProcessArchived.vue
src/views/Process/ProcessList.vue
src/views/ProcessLaboralesOrdinarios/ProcessLaboralesArchived.vue
src/views/ProcessLaboralesOrdinarios/ProcessLaboralesList.vue

Se corrigió error que hacia que la busqueda en las diferentes listas de procesos fuese lenta y se quedara esperando

FUSION [JUR-88] lentitud busqueda process list fixed con release-1.1.0

---

src/components/Process/Modals/ModalTerminarProceso.vue
src/views/Process/ProcessList.vue
src/views/Process/ShowProcess.vue
src/views/ProcessLaboralesOrdinarios/ProcessLaboralesList.vue

Se agrego botón para termionar un proceso directamente desde lista de porocesos y tambien en info de proceso.

FUSION [JUR-97] boton terminar proceso con release-1.1.0

---

src/assets/css/custom.css
src/components/Process/Modals/ModalTerminarProceso.vue
src/views/Process/ProcessList.vue
src/views/Process/ShowProcess.vue
src/views/ProcessLaboralesOrdinarios/ProcessLaboralesList.vue

Se corrigió nombre de botón terminar procesos. 
Se eliminó el botón de terminar proceso cuando un proceso está archivado. 
Se eliminaron campos relacionados con audiencias cuando la actuación es de tipo terminar. 
Se agregaron modales de confirmación para poder terminar un proceso.

FUSION [JUR-101] feature organizacion de detalles proceso terminado con release-1.1.0

---

src/views/Process/ShowProcess.vue

Se agregó función para obtener los perfiles de la clínica en el proceso, en el apartado de mounted del componente de showprocess

FUSION [JUR-106] Hotfix tipo de actuación con main

---

src/views/Process/ShowProcess.vue

Se agregó href al nombre d elos links en la pestaña de documentos del proceso.

FUSION [JUR-96] href para nombre de link con release-1.1.0

---

src/components/Process/ShowProcessComponents/ProcessEjecutivo/CostosCuantiasProcesoEjecutivo.vue
src/components/Process/ShowProcessComponents/ProcessLaborales/CostosCuantiasProcesoLaboral.vue
src/components/Process/ShowProcessComponents/ProcessMedico/CostosCuantiasProcesoMedico.vue
src/views/Process/ShowProcess.vue

Se agregaron los campos nuevos en cuantías según excel.
Se acomoda bug al cancelar edición de cuantías y al calcular el total

FUSION [JUR-105] acomodar cuantias segun excel y nuevas columnas con release-1.1.0

---

src/components/Process/ShowProcessComponents/ProcessEjecutivo/CostosCuantiasProcesoEjecutivo.vue
src/components/Process/ShowProcessComponents/ProcessLaborales/CostosCuantiasProcesoLaboral.vue
src/components/Process/ShowProcessComponents/ProcessMedico/CostosCuantiasProcesoMedico.vue
src/views/Process/ShowProcess.vue

se agregan variables temporales para editar cuantias, se separa valor Otros en cuantías de procesos de responsabilidad médica

FUSION [JUR-107] separar otros valores procesos responsabilidad m con release-1.1.0

---

src/views/Process/ShowProcess.vue

Se agregó funcionalidad que actualiza las variables de la tabla de links si el link no tiene https

FUSION [JUR-108] se actualizan links sin https con release-1.1.0

---

src/views/Process/ShowProcess.vue

Se habilitan botones para editar procesos archivados y pólizas archivadas, se agrega funcion para eliminar polizas de procesos

[JUR-112] funcionalidad editar procesos archivados con main

---

src/FackApi/json/SideBar.json
src/components/Process/ShowProcessComponents/ProcessEjecutivo/CostosCuantiasProcesoEjecutivo.vue
src/locales/sp.json
src/router/index.js
src/views/Process/ShowProcess.vue
src/views/ProcessOtros/ProcessOtrosArchived.vue
src/views/ProcessOtros/ProcessOtrosList.vue

Se agrega módulo que contiene lista de otros tipos de procesos diferentes a laborales y médicos.
Se agrega clase disabled para el botón de agregar actuación para los procesos que están archivados.

FUSION [JUR-111] feature modulo para lista de otros tipos de proces con release-1.1.0

---

src/FackApi/json/SideBar.json
src/assets/css/custom.css
src/components/xray/menus/ListStyle1.vue
src/components/xray/sidebars/SideBarStyle1.vue
src/views/AuthPages/Default/Forms/SignIn1Form.vue

se agrega funcionalidad para renderizar el sidebar de forma dinámica dependiendo del perfil del usuario loggeado

FUSION [JUR-121] feature sidebar segun perfiles con ANS-release-1.1.0

---

src/FackApi/json/SideBar.json
src/assets/css/custom.css
src/components/xray/menus/ListStyle1.vue
src/components/xray/sidebars/SideBarStyle1.vue
src/locales/sp.json
src/views/AuthPages/Default/Forms/SignIn1Form.vue

Se crean los modulos principales en el sidebar dinámico para ANS

FUSION [JUR-122] feature crear nuevos modulos de ans para sidebar con ANS-release-1.1.0

---

src/FackApi/json/SideBar.json
src/router/index.js
src/views/AuthPages/Default/Forms/SignIn1Form.vue
src/views/AuthPages/Default/Forms/SignUp1Form.vue
src/views/AuthPages/Default/SignUp1.vue

Se implementa vista para registro de un usuario con navegación entre el login y esta

FUSION [JUR-123] vista registrar cuenta con ANS-release-1.1.0

---

package-lock.json
src/FackApi/json/SideBar.json
src/locales/sp.json
src/router/index.js
src/views/User/AddUser.vue

Se implementa el módulo para crear usuario en el sidebar y se acomodan inputs en vista de creación de usuario

FUSION [JUR-124] módulo crear usuario con ANS-release-1.1.0

---

package-lock.json
src/FackApi/json/SideBar.json
src/locales/sp.json
src/router/index.js
src/views/User/AddUser.vue
src/views/User/UserList.vue

Se cambia el lugar donde se settea la variable de totalRows para que la paginación de la lista funcione correctamente. Se añaden clases de estilos a los filtros

FUSION [JUR-125] bugfix paginacion de listado de usuarios no funcio con ANS-release-1.1.0

---

src/FackApi/json/SideBar.json
src/router/index.js
src/views/User/ProfileEdit.vue
src/views/User/UserList.vue

ahora se puede editar cualquier tipo de usuario, se cambia ruta de lista de usuarios

FUSION [JUR-126] campos para editar usuario con ANS-release-1.1.0

---

src/FackApi/json/SideBar.json
src/router/index.js
src/views/User/AddUser.vue
src/views/User/ProfileEdit.vue
src/views/User/UserList.vue

Se cambiaron los nombres de algunas variables para la creación del objeto user al crear un usuario nuevo.

FUSION [JUR-127] bugfix al crear usuario agregarle las nuevas colu con ANS-release-1.1.0

---

src/views/Dashboards/DashboardGerencia.vue

Fusión [JUR-132]-feature-quitar-tres-numeros-a-los-datos-generales-en-panel-gerencial con release-1.2.0

---

src/FackApi/json/SideBar.json
src/locales/sp.json
src/router/index.js
src/views/Cases/MyCases.vue

Fusión [JUR-145]-feature-como-cliente-deseo-poder-listar-mis-casos-para-tene... con ANS-release-1.1.0

---

src/views/AuthPages/Default/Forms/SignIn1Form.vue
src/views/Cases/MyCases.vue

Fusión [JUR-149]-bugfix-cuando-entro-como-cliente-me-carga-el-… con ANS-release-1.1.0

---

.env.production
docker-compose.yml
src/main.js
src/views/AuthPages/Default/Forms/SignUp1Form.vue
src/views/Cases/ShowCase.vue

Se organiza temas de dockerización del front
https://desarrollo-ospedale.atlassian.net/browse/JUR-130

Fusión [JUR-130] se organiza dockerización con ANS-release-1.1.0

---

src/views/User/AddUser.vue
src/views/User/ProfileEdit.vue

Se organiza las condiciones necesarias en el user create y edit. Así mismo las validaciones. Ahora se obtienen los perfiles desde la base de datos
https://desarrollo-ospedale.atlassian.net/browse/JUR-215

Fusión [JUR-215] se organizan detalles en users con ANS-release-1.1.0

---

src/assets/css/custom.css
src/router/index.js
src/views/AuthPages/Default/SignIn1.vue
src/views/Cases/components/FormCase.vue

https://desarrollo-ospedale.atlassian.net/browse/JUR-243

Fusión [JUR-243] bugfix problema redireccionamiento con ANS-release-1.1.0

---

src/FackApi/json/SideBar.json
src/router/index.js

https://desarrollo-ospedale.atlassian.net/browse/JUR-246

Fusión [JUR-246]-bugfix-agregar-opcion-agregar-proceso-linea-labora con release-1.2.0

---

src/router/index.js
src/views/AuthPages/Default/Forms/SignIn1Form.vue
src/views/AuthPages/Default/SignIn1.vue

Ahora cuando se da clic en "Ver caso" o puede ser cualquier link y si no está logueado, el sistema esperará a que se loguee y ahí si lo redirige adonde debería.
https://desarrollo-ospedale.atlassian.net/browse/JUR-223

Fusión [JUR-223]-se-organiza-redireccion con ANS-release-1.1.0

---

src/assets/css/custom.css
src/views/Cases/ShowCase.vue

Fusión [JUR-257]-feature-en-ambiente-de-servidor-el-campo-fecha-no-funciona con ANS-release-1.1.0

---

src/FackApi/json/SideBar.json

https://desarrollo-ospedale.atlassian.net/browse/JUR-263

Fusión [JUR-263]-hotfix-no-se-muestran-los-procesos-laborales con release-1.3.0

---

src/views/Process/ProcessArchived.vue
src/views/Process/ProcessList.vue
src/views/ProcessLaboralesOrdinarios/ProcessLaboralesArchived.vue
src/views/ProcessLaboralesOrdinarios/ProcessLaboralesList.vue

Ahroa el proceso se eliminación de caso es mas restrictivo y se guarda traza de la info que se "elimina" por sofdelete
https://desarrollo-ospedale.atlassian.net/browse/JUR-266

Fusión [JUR-266]-feature-mejorar-proceso-de-eliminacion-de-proceso con release-1.3.0

---

src/views/Cases/GraphsAndReports.vue
src/views/Cases/components/CumplimientoTabla.vue

https://desarrollo-ospedale.atlassian.net/browse/JUR-262?atlOrigin=eyJpIjoiZjEzODExMTA2NTBkNGQzMDhjNzM0YTJhZGRmZWUyZTEiLCJwIjoiaiJ9

Fusión [JUR-262] feature tabla con datos cumplimiento por clinicas con ANS-release-1.1.0

---

src/views/Cases/GraphsAndReports.vue
src/views/Cases/components/OportunidadDias.vue

https://desarrollo-ospedale.atlassian.net/browse/JUR-261?atlOrigin=eyJpIjoiZGJlNTIzODI2Njc2NDFiY2FhYjNkZjkxYjE4YzNkYzYiLCJwIjoiaiJ9

Fusión [JUR-259]-feature-grafica-oportunidad-de-dias con release-1.3.0

---

src/views/Cases/GraphsAndReports.vue
src/views/Cases/components/DistribucionServicios.vue

https://desarrollo-ospedale.atlassian.net/browse/JUR-261?atlOrigin=eyJpIjoiYzA0NWRjZjlhZmJjNDg0ZGJkMTczNjdkMTE4NzY3Y2MiLCJwIjoiaiJ9

Fusión [JUR-261]-feature-distribucion-de-servicios-juridico con release-1.3.0

---

src/FackApi/json/SideBar.json
src/views/Cases/components/CumplimientoCasos.vue
src/views/Cases/components/CumplimientoTabla.vue
src/views/Cases/components/GraficoTotalSubactividad.vue
src/views/Cases/components/OportunidadDias.vue

https://desarrollo-ospedale.atlassian.net/browse/JUR-267

Fusión [JUR-267] feature eliminar menu otros procesos con release-1.3.0

---

src/FackApi/json/SideBar.json
src/components/Process/ShowProcessComponents/ProcessEjecutivo/CostosCuantiasProcesoEjecutivo.vue
src/components/Process/ShowProcessComponents/ProcessLaborales/CostosCuantiasProcesoLaboral.vue
src/components/Process/ShowProcessComponents/ProcessMedico/CostosCuantiasProcesoMedico.vue

https://desarrollo-ospedale.atlassian.net/browse/JUR-275

Fusión [JUR-275] feature estimaciones en pestana costos y cuantias con release-1.3.0

---

src/FackApi/json/SideBar.json
src/components/Process/Modals/ModalTerminarProceso.vue
src/components/Process/ShowProcessComponents/ProcessEjecutivo/CostosCuantiasProcesoEjecutivo.vue
src/components/Process/ShowProcessComponents/ProcessLaborales/CostosCuantiasProcesoLaboral.vue
src/components/Process/ShowProcessComponents/ProcessMedico/CostosCuantiasProcesoMedico.vue

https://desarrollo-ospedale.atlassian.net/browse/JUR-274

Fusión [JUR-274] feature modal fecha terminado diferente con release-1.3.0

---

src/layouts/Layout1.vue

https://desarrollo-ospedale.atlassian.net/browse/JUR-136

Fusión [JUR-136] feature subir foto en plataforma con release-1.3.0

---

src/layouts/Layout1.vue
src/views/Process/AddProcess.vue

https://desarrollo-ospedale.atlassian.net/browse/JUR-67

Fusión [JUR-67] bugfix provisiones constituidas van en el proceso con release-1.3.0

---

src/views/Cases/AllCases.vue

https://desarrollo-ospedale.atlassian.net/browse/JUR-273

Fusión [JUR-273] feature importar casos de almera con release-1.4.0

---

src/FackApi/json/SideBar.json
src/views/Process/ShowProcess.vue

https://desarrollo-ospedale.atlassian.net/browse/JUR-293

Fusión [JUR-293] feature volver a panel otros con release-1.5.0

---

src/FackApi/json/SideBar.json
src/views/Process/AddProcess.vue
src/views/Process/ShowProcess.vue

https://desarrollo-ospedale.atlassian.net/browse/JUR-286

Fusion [JUR-286] feature descripcion del siniestro en mayuscula con release-1.5.0.

---

package-lock.json
package.json
src/FackApi/json/SideBar.json
src/views/Process/AddProcess.vue
src/views/Process/ShowProcess.vue

https://desarrollo-ospedale.atlassian.net/browse/JUR-188

Fusión [JUR-188] feature campo de descripcion siniestro tipo word release-1.5.0

---

package-lock.json
package.json
src/FackApi/json/SideBar.json
src/views/Cases/ShowCase.vue
src/views/Process/AddProcess.vue
src/views/Process/ShowProcess.vue

https://desarrollo-ospedale.atlassian.net/browse/JUR-238

Fusión [JUR-238] bugfix archivo no aparece en el seguimiento con release-1.5.0

---

package-lock.json
package.json
src/FackApi/json/SideBar.json
src/views/Cases/ShowCase.vue
src/views/Process/AddProcess.vue
src/views/Process/ShowProcess.vue

https://desarrollo-ospedale.atlassian.net/browse/JUR-93

Fusión [JUR-93]feature al escribir el numero de radicado consulte la bd para verificar existencia del mismo con release-1.5.0

---

package-lock.json
package.json
src/FackApi/json/SideBar.json
src/views/Cases/ShowCase.vue
src/views/Process/AddProcess.vue
src/views/Process/ShowProcess.vue

https://desarrollo-ospedale.atlassian.net/browse/JUR-295

Fusion [JUR-295] bugfix abogado no puede editar proceso archivado con release-1.5.0.

---

src/views/Process/AddProcess.vue
src/views/Process/ShowProcess.vue

https://desarrollo-ospedale.atlassian.net/browse/JUR-301

Fusión [JUR-301]-bugfix-no-guarda-colaborador-ips-save-and-update con release-1.5.0

---

src/views/Process/AddProcess.vue
src/views/Process/ShowProcess.vue

https://desarrollo-ospedale.atlassian.net/browse/JUR-298

Fusion [JUR-298] feature mostrar las siguientes columnas laborales con release-1.5.0

---

src/components/Process/Modals/ModalTerminarProceso.vue
src/views/Process/AddProcess.vue
src/views/Process/ShowProcess.vue

https://desarrollo-ospedale.atlassian.net/browse/JUR-297

Fusión [JUR-297] feature nuevas opciones en tipos terminacion con release-1.5.0

---

src/components/Process/Modals/ModalTerminarProceso.vue
src/views/Process/AddProcess.vue
src/views/Process/ShowProcess.vue

https://desarrollo-ospedale.atlassian.net/browse/JUR-299

Fusión [JUR-299] feature quitar obligatoriedad de fecha conciliacion prejudicial release-1.5.0

---

src/components/Process/Modals/ModalTerminarProceso.vue
src/views/Process/AddProcess.vue
src/views/Process/ShowProcess.vue

https://desarrollo-ospedale.atlassian.net/browse/JUR-300

Fusión [JUR-300] feature automaticamente guardar el abogado lider con release-1.5.0

---

src/components/Process/Modals/ModalTerminarProceso.vue
src/views/Process/AddProcess.vue
src/views/Process/ShowProcess.vue

https://desarrollo-ospedale.atlassian.net/browse/JUR-302

Fusión [JUR-302] feature preescrito si o no con release-1.5.0

---

package-lock.json
package.json
src/FackApi/json/SideBar.json
src/components/Process/Modals/ModalTerminarProceso.vue
src/views/Cases/ShowCase.vue
src/views/Process/AddProcess.vue
src/views/Process/ShowProcess.vue

Tareas:
https://desarrollo-ospedale.atlassian.net/browse/JUR-302
https://desarrollo-ospedale.atlassian.net/browse/JUR-300
https://desarrollo-ospedale.atlassian.net/browse/JUR-299
https://desarrollo-ospedale.atlassian.net/browse/JUR-297
https://desarrollo-ospedale.atlassian.net/browse/JUR-298
https://desarrollo-ospedale.atlassian.net/browse/JUR-296
https://desarrollo-ospedale.atlassian.net/browse/JUR-301
https://desarrollo-ospedale.atlassian.net/browse/JUR-295
https://desarrollo-ospedale.atlassian.net/browse/JUR-93
https://desarrollo-ospedale.atlassian.net/browse/JUR-238
https://desarrollo-ospedale.atlassian.net/browse/JUR-188
https://desarrollo-ospedale.atlassian.net/browse/JUR-286
https://desarrollo-ospedale.atlassian.net/browse/JUR-293 …

Fusión main con release-1.5.0

---

src/views/Process/ShowProcess.vue

tareas:
https://desarrollo-ospedale.atlassian.net/browse/JUR-304

Fusión release-1.5.0 con main

---

src/views/Process/ShowProcess.vue

https://desarrollo-ospedale.atlassian.net/browse/JUR-309

fusión [JUR-309]-feature-organizar-detalle-de-proceso con release-1.5.0

---

src/views/Process/ShowProcess.vue

https://desarrollo-ospedale.atlassian.net/browse/JUR-311

Fusión [JUR-311]-bugfix-error-en-el-total-de-costas-y-sentencia-final con release-1.5.0

---

src/views/Process/ShowProcess.vue

https://desarrollo-ospedale.atlassian.net/browse/JUR-314

Fusión [JUR-314] bugfix campos obligatorios al editar proceso con release-1.5.0

---

src/components/Process/ShowProcessComponents/ProcessEjecutivo/CostosCuantiasProcesoEjecutivo.vue
src/components/Process/ShowProcessComponents/ProcessLaborales/CostosCuantiasProcesoLaboral.vue
src/components/Process/ShowProcessComponents/ProcessMedico/CostosCuantiasProcesoMedico.vue
src/views/Policies/ShowPolicy.vue
src/views/Process/ShowProcess.vue

https://desarrollo-ospedale.atlassian.net/browse/JUR-313

Fusión [JUR-313] feature mejoras en el detalle de proceso con release-1.6.0.

---

src/components/Process/ShowProcessComponents/ProcessEjecutivo/CostosCuantiasProcesoEjecutivo.vue
src/components/Process/ShowProcessComponents/ProcessLaborales/CostosCuantiasProcesoLaboral.vue
src/components/Process/ShowProcessComponents/ProcessMedico/CostosCuantiasProcesoMedico.vue
src/views/Policies/ShowPolicy.vue
src/views/Process/ShowProcess.vue

Tareas:
https://desarrollo-ospedale.atlassian.net/browse/JUR-313

Fusión release-1.6.0 con main

---

src/views/Process/ShowProcess.vue

…inalizados
https://desarrollo-ospedale.atlassian.net/browse/JUR-316

fusión [JUR-316]-feature-permitir-al-usuario-administrador-editar-procesos-f… release-1.6.0

---

src/views/Dashboards/Dashboard1.vue
src/views/Process/ProcessArchived.vue
src/views/Process/ProcessList.vue
src/views/Process/ShowProcess.vue
src/views/ProcessLaboralesOrdinarios/ProcessLaboralesArchived.vue
src/views/ProcessLaboralesOrdinarios/ProcessLaboralesList.vue
src/views/ProcessOtros/ProcessOtrosArchived.vue
src/views/ProcessOtros/ProcessOtrosList.vue

https://desarrollo-ospedale.atlassian.net/browse/JUR-317

fusión [JUR-317] feature organizar las fechas de ingreso con release-1.6.0

---

src/components/Process/ShowProcessComponents/ProcessEjecutivo/CostosCuantiasProcesoEjecutivo.vue
src/components/Process/ShowProcessComponents/ProcessLaborales/CostosCuantiasProcesoLaboral.vue
src/components/Process/ShowProcessComponents/ProcessMedico/CostosCuantiasProcesoMedico.vue
src/views/Cases/AddCaseAbogado.vue
src/views/Process/AddProcess.vue
src/views/Process/ShowProcess.vue

https://desarrollo-ospedale.atlassian.net/browse/JUR-320

Fusión [JUR-320] feature admin puede editar todo de los procesos archivados con release-1.6.0

---

package.json

https://desarrollo-ospedale.atlassian.net/browse/JUR-327
Ahora se exporta en la carpeta app y dist no se toca

Fusión [JUR-327] se organiza package.json con release-1.6.0

---

src/components/xray/charts/GraficaProcesosPorClinica.vue
src/components/xray/navbars/NavBarStyle1.vue
src/views/Dashboards/DashboardGerencia.vue

https://desarrollo-ospedale.atlassian.net/browse/JUR-324

fusión [JUR-324] feature filtro por tipo de proceso responsabilidad medica, laborales, otros con release-1.6.0

---

src/components/xray/charts/GraficaInformacionPorRiesgo.vue
src/components/xray/charts/GraficaProcesosPorAseguradora.vue
src/components/xray/charts/GraficaProcesosPorClinica.vue
src/components/xray/charts/GraficaProcesosPorEspecialidad.vue
src/components/xray/charts/GraficaProcesosPorEstados.vue
src/components/xray/navbars/NavBarStyle1.vue
src/views/Dashboards/Dashboard1.vue
src/views/Dashboards/DashboardGerencia.vue

https://desarrollo-ospedale.atlassian.net/browse/JUR-325

Fusión [JUR-325] feature filtro por clinica y tipo de proceso nivel de exito con release-1.6.0

---

src/views/Dashboards/Dashboard1.vue

https://desarrollo-ospedale.atlassian.net/browse/VIAT-326

fusión JUR 336 feature organizar datos tabla nivel exito con release-1.7.0

---

src/views/User/AddUser.vue
src/views/User/ProfileEdit.vue

https://desarrollo-ospedale.atlassian.net/browse/JUR-349

Fusión [JUR-349] se agrega nit con release-1.7.0

---

src/views/User/AddUser.vue
src/views/User/ProfileEdit.vue

https://desarrollo-ospedale.atlassian.net/browse/JUR-346

Fusión [JUR-346] feature quitar fecha de nacimiento con release-1.7.0

---

src/components/xray/sidebars/SideBarStyle1.vue
src/views/User/AddUser.vue
src/views/User/ProfileEdit.vue

https://desarrollo-ospedale.atlassian.net/browse/JUR-350

Fusión [JUR-350] feature contrasena por defecto con release-1.7.0

---

src/router/index.js

https://desarrollo-ospedale.atlassian.net/browse/JUR-352

Fusión [JUR-352] se implementa solución alterna con release-1.7.0

---

src/views/Cases/AddCaseAbogado.vue
src/views/Cases/ShowCase.vue
src/views/Dashboards/Dashboard1.vue

https://desarrollo-ospedale.atlassian.net/browse/JUR-338

Fusión [JUR-338] se agrega validaciones con release-1.7.0

---

package.json
src/views/Process/ShowProcess.vue

https://desarrollo-ospedale.atlassian.net/browse/JUR-355

Fusión [JUR-355]-bugfix-no-se-muestra-el-tipo-de-identificacion-cor con release-1.8.0

---

package.json
src/views/Process/ShowProcess.vue

Tareas:
https://desarrollo-ospedale.atlassian.net/browse/JUR-355

Fusión release-1.8.0 con main

---

src/views/Cases/AddCaseAbogado.vue

https://desarrollo-ospedale.atlassian.net/browse/JUR-353
Ahora se pide primero la clínica y con base en esta, se traen los clientes que le pertenecen

Fusión [JUR-353]-feature-traer-usuarios-luego-de-seleccionar-clinic con release-1.8.0

---

package.json
src/views/Process/AddProcess.vue
src/views/Process/EditProcess.vue
src/views/Process/ShowProcess.vue

https://desarrollo-ospedale.atlassian.net/browse/JUR-351

Fusión [JUR-351]-feature-eps-en-el-proceso-de-responsabilidad-medic con release-1.8.0

---

package-lock.json
package.json
src/assets/css/custom.css
src/views/Cases/AddCaseAbogado.vue

https://desarrollo-ospedale.atlassian.net/browse/JUR-357
Se agrega al formulario de agregar caso por el abogado la fecha de solicitud

Fusión [JUR-357]-feature-fecha-solicitud-en-el-formulario-de-crear con release-1.8.0

---

src/views/Cases/AllCases.vue
src/views/Cases/AssignedCases.vue
src/views/Cases/CasesToAssing.vue
src/views/Cases/MyCases.vue
src/views/Cases/components/FormCase.vue

https://desarrollo-ospedale.atlassian.net/browse/JUR-365
Ahora se envía los datos necesarios para que el componente funciones

Fusión [JUR-365]-feature-permitir-modificar-la-fecha-de-solicitud con release-1.8.0

---

src/views/Cases/AssignedCases.vue
src/views/Cases/components/FormCase.vue

https://desarrollo-ospedale.atlassian.net/browse/JUR-370
Ahora la opción de "en espera" en mis asignacioens se elimina. Ahora fecha de solicitud si se envía.

Fusión [JUR-370]-bugfix-no-se-esta-enviando-la-fecha-de-solicitud-c con release-1.9.0

---

package.json
src/views/Cases/AssignedCases.vue
src/views/Cases/components/FormCase.vue
src/views/Dashboards/Dashboard1.vue
src/views/Process/ShowProcess.vue

Tareas:
https://desarrollo-ospedale.atlassian.net/browse/JUR-370

Fusión release-1.9.0 con main

---

src/views/Cases/AssignedCases.vue

https://desarrollo-ospedale.atlassian.net/browse/JUR-375

Fusión [JUR-375] se organiza el cambio de estado con main

---

src/layouts/Layout1.vue

https://desarrollo-ospedale.atlassian.net/browse/JUR-373

Fusión [JUR-373]-bugfix-cuando-se-elimina-el-storage con release-1.9.0

---

package.json
src/FackApi/json/SideBar.json
src/locales/sp.json
src/views/Cases/ShowCase.vue
src/views/Cases/components/FormCase.vue

https://desarrollo-ospedale.atlassian.net/browse/JUR-372
Se organizan algunos detalles del front.

Fusión [JUR-372]-feature-cambios-sencillos con release-2.0.0
